# Generated by Django 3.2.12 on 2022-02-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=30)),
                ("experience", models.CharField(max_length=50)),
                ("cv", models.FileField(upload_to="User_CVs")),
            ],
        ),
    ]
